Feature/about section
OrenMoveo/Epicure pull request #13
Opened 2024-01-31 20:38 UTC by OrenMoveo

# About Section Feature Fixed

## This PR Includes
- Implemented OSOT logic to ensure mobile and desktop UI compatibility, preventing any potential UI breaks.
- Utilized constants to eliminate unnecessary padding and enhance overall design consistency.

כ
## Example
![Mobile](https://github.com/OrenMoveo/Epicure/assets/156906187/426df510-c6c3-496e-b24a-6781c1520223)
*Mobile view*

![Desktop](https://github.com/OrenMoveo/Epicure/assets/156906187/01af1354-3e77-4157-bbc5-671fe8247d20)
*Desktop view*

2024-01-31 21:21 UTC, nitzanpap requested changes
Please fix the following errors in your app:
1. 
![Screenshot from 2024-01-31 23-09-54](https://github.com/OrenMoveo/Epicure/assets/87342833/7de0ee7b-820d-47bb-bf4b-78100e1e7268)

You didn't add a unique key to your map() functions that render items.
[Read here about why it happens, and what are good patterns vs anti-patterns of this issue.](https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js)
2. 
![Screenshot from 2024-01-31 23-10-34](https://github.com/OrenMoveo/Epicure/assets/87342833/64f2bf83-c20c-4e5f-853e-ac730ed45256)
Since you changed the names of your svgs, there is now a mismatch when you import them, therefore they broke. Implement the fix.

3. Note that I approved and merged all the other PRs, but please make sure to overview them briefly and fix the small changes that I marked as a request for change. regular comments are only there for you information and you do not need to fix or refactor according to them.

2024-02-01 08:04 UTC, OrenMoveo commented
> Please fix the following errors in your app: 1. ![Screenshot from 2024-01-31 23-09-54](https://private-user-images.githubusercontent.com/87342833/301308964-7de0ee7b-820d-47bb-bf4b-78100e1e7268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzIxMzIsIm5iZiI6MTcwNjc3MTgzMiwicGF0aCI6Ii84NzM0MjgzMy8zMDEzMDg5NjQtN2RlMGVlN2ItODIwZC00N2JiLWJmNGItNzgxMDBlMWU3MjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWYwNWFmZmFjZTMyYzY1YjNlMzNkODk0M2MwZTk0MjhlYzIxN2ZjMjEzODliMmRlMjdjYWM3NDUwMWI2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fgcatdt8k1-L08xukcng3L9Mbcb_GGF-yRv7atLrRhQ)
> 
> You didn't add a unique key to your map() functions that render items. [Read here about why it happens, and what are good patterns vs anti-patterns of this issue.](https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js) 2. ![Screenshot from 2024-01-31 23-10-34](https://private-user-images.githubusercontent.com/87342833/301310030-64f2bf83-c20c-4e5f-853e-ac730ed45256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzIxMzIsIm5iZiI6MTcwNjc3MTgzMiwicGF0aCI6Ii84NzM0MjgzMy8zMDEzMTAwMzAtNjRmMmJmODMtYzIwYy00ZTVmLTg1M2UtYWM3MzBlZDQ1MjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjczOWJhODM1Yjg3NWNmNTk0MzRlZjQ4YWIwNGY5MTYwMDA4OTUwOTM0MzQxM2IwYzczMzNiZTRiOTYyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eH94cx85UF8GE7ZVMFBoAwDA_53yp0Y0INuRCpoIIag) Since you changed the names of your svgs, there is now a mismatch when you import them, therefore they broke. Implement the fix.
> 
> 3. Note that I approved and merged all the other PRs, but please make sure to overview them briefly and fix the small changes that I marked as a request for change. regular comments are only there for you information and you do not need to fix or refactor according to them.


1. icon fixed.
2. overflow fixed.
3. keyId error fixed.
4. homepage gap fixed.
@nitzanpap

2024-02-01 11:51 UTC, OrenMoveo commented
@nitzanpap 
keyId pattern fixed.

2024-02-03 20:32 UTC, nitzanpap approved these changes

2024-02-03 20:32 UTC, merged